language: go
go:
  - 1.8.x

branches:
  only:
    - master
    - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"

before_install:
  - export PATH=$PATH:$GOPATH/bin
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go build .
